name 'stanlee-tomcat'
version '0.0.1'
author 'Johan Lyheden'
license 'Apache License 2.0'
project_page 'https://github.com/stanlee/puppet-tomcat'
source 'https://github.com/stanlee/puppet-tomcat'
summary 'Tomcat module'
description 'A module for managing Tomcat 6 and 7'
dependency 'ripienaar/concat', '>=0.2.0'
dependency 'puppetlabs/stdlib', '>=3.x'
