name 'stanlee-tomcat'
version '0.0.1'

author 'Johan Lyheden'
license ''
project_page 'https://github.com/stanlee/puppet-tomcat'
source 'https://github.com/stanlee/puppet-tomcat'
summary ''
description ''
dependency 'ripienaar/concat', '==0.2.0'
dependency 'puppetlabs/stdlib', '==3.2.0'
